name:                basicHttp
version:             0.1.0.0
github:              "githubuser/basicHttp"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2017 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/basicHttp#readme>

dependencies:
- base >= 4.7 && < 5
- wai >= 3.2 && < 4
- warp >= 3.2 && < 4
- http-types >= 0.9.0

library:
  source-dirs: src

executables:
  basicHttp-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - basicHttp

tests:
  basicHttp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - basicHttp
